<a href="https://colab.research.google.com/github/Abhishek1shrivastava/Data-science/blob/main/numpy_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arrr = np.array([[1,2,3],[4,5,6],[7,8,9],[0,12,13]])
print("array without slicing:-\n",arrr)
print("type of array is :-",type(arrr))
print("dimantion of array is :-",(arrr.ndim))
print("shape of the array is :-",(arrr.shape))
print("size of the array is :-",(arrr.size))
print("type of element in array is :-",(arrr.dtype))

array without slicing:-
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 12 13]]
type of array is :- <class 'numpy.ndarray'>
dimantion of array is :- 2
shape of the array is :- (4, 3)
size of the array is :- 12
type of element in array is :- int64


In [ ]:
print(arrr[2,-1])

9


slice the first row onwards


In [ ]:
print(arrr[1:4])

[[ 4  5  6]
 [ 7  8  9]
 [ 0 12 13]]


slice all the item from the first column onward


In [ ]:
print(arrr[0:4,0:1])

[[1]
 [4]
 [7]
 [0]]
