<a href="https://colab.research.google.com/github/Abhishek1shrivastava/Data-science/blob/main/numpy_excersises_lab(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np

Q.1:- wap in numpy to get the Numpy Version

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


Q.2:- Wap in Numpy to test whether none of the element of a given array are Zero

In [ ]:
# its is program to working with linspace() fuction in numpy:
import numpy as np
arr = np.linspace(0,1,6)
print(arr)

[0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
# import numpy as np
ar = np.array([1,2,3, 0,4,5])
for i in range(len(ar)):
  if (ar[i]!= 0):
      print(ar[i])
  else:
    print("yes 0 exists")

    # exit()



1
2
3
yes 0 exists
4
5


Q.3  :- wap in numpy to create an element -wise comparision(greater,greater_equal,less_equal) of two given array


In [ ]:
import numpy as np
a = np.array([1,4,5,2])
b = np.array([2,3,5,1])
for i in range(len(a)):
  if(a[i]>b[i]):
    print("a is greater")
  elif(a[i]>=b[i]):
    print("a is greater equal")
  elif(a[i]<b[i]):
    print("a is less")
  else:
    print("a is less greater")


a is less
a is greater
a is greater equal
a is greater


Q.4:- Write a NumPy program to create an array with the values
1, 7, 13, 105 and determine the size of the memory occupied
by the array.

In [ ]:
import numpy as np
value = np.array([1,7,13,105])
#In array each element has occupied 8 Bytes in memory
print( "the value of created array is" ,value)
size = value.nbytes
print("The size of the memory occupied by the array is:- ",size)


the value of created array is [  1   7  13 105]
The size of the memory occupied by the array is:-  32


Q.5:-Write a NumPy program to create an array of integers
from 30 to 70.


In [ ]:
import numpy as np
arrr = np.arange(30,70)
print(" array of integers from 30 to 70. is:-",arrr)

 array of integers from 30 to 70. is:- [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


Q.6:-Write a NumPy program to create an array of all even
integers from 30 to 70.

In [ ]:
import numpy as np
arrrr = np.arange(30,70,2).reshape(4,5)
print(" array of all even integers from 30 to 70. is:-\n",arrrr)

 array of all even integers from 30 to 70. is:-
 [[30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]]


Q.7:-Write a NumPy program to create a 3x3 identity matrix.

In [ ]:
import numpy as np
#I_M = np.array([[1,0,0],[0,1,0],[0,0,1]])
#print(I_M)
I_M= np.identity(3,dtype=int)#this fuction take float value by default
print(I_M)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


!!!! Exercise question to arange array in shape like(3X3) using reshape() fuction

In [ ]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 